# Generated by Django 4.0 on 2022-01-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0005_activation_key_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRegistrationProfile',
            fields=[
                ('registrationprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.registrationprofile')),
            ],
            options={
                'verbose_name': 'активация',
                'verbose_name_plural': 'регистрация',
            },
            bases=('registration.registrationprofile',),
        ),
    ]
