# Generated by Django 4.0 on 2022-01-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('email_send_at', models.DateTimeField(blank=True, null=True, verbose_name='дата отправки email')),
                ('email_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='email обработано')),
                ('sms_send_at', models.DateTimeField(blank=True, null=True, verbose_name='дата отправки sms')),
                ('sms_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='sms обработано')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.position', verbose_name='позиция')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule', verbose_name='правило')),
            ],
            options={
                'verbose_name': 'инцидент',
                'verbose_name_plural': 'оповещения',
            },
        ),
    ]
