# Generated by Django 4.0 on 2022-01-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_alter_device_add_position_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='долгота (градусы)')),
                ('longitude_type', models.CharField(choices=[('E', 'Восточная'), ('W', 'Западная')], default='N', max_length=1, verbose_name='тип долготы')),
                ('latitude', models.FloatField(verbose_name='широта (градусы)')),
                ('latitude_type', models.CharField(choices=[('N', 'Северная'), ('S', 'Южная')], default='E', max_length=1, verbose_name='тип широты')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='расстояние (км)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='скорость (км/ч)')),
                ('acceleration', models.FloatField(blank=True, null=True, verbose_name='ускорение (м/с^2)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='время (с)')),
                ('is_broken', models.BooleanField(default=False, verbose_name='ложная точка')),
                ('parameters', models.TextField(blank=True, null=True, verbose_name='другие параметры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='трекер')),
            ],
            options={
                'verbose_name': 'точка',
                'verbose_name_plural': 'путевые точки трекеров',
                'ordering': ['created_at'],
            },
        ),
    ]
