# Generated by Django 4.0 on 2022-01-07 14:05

import apps.devices.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='название устройства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('image', models.FileField(blank=True, null=True, upload_to=apps.devices.models.device_upload_path, verbose_name='изображение')),
                ('add_position_password', models.CharField(default='KHOLN', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='', regex=re.compile('^[0-9A-Z]+$'))], verbose_name='идентификатор')),
                ('width', models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)], verbose_name='толщина линии (px)')),
                ('color_rgb', models.CharField(blank=True, default='#c41e3a', max_length=255, null=True, verbose_name='цвет линии (RGB)')),
                ('connection_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес подключения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('protocol', models.CharField(choices=[('nmea', 'Nmea'), ('traccar', 'Traccar'), ('autofon', 'Autofon Mayak 5.x')], max_length=30, null=True, verbose_name='протокол')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.customuser')),
            ],
            options={
                'verbose_name': 'трекер',
                'verbose_name_plural': 'трекеры',
                'ordering': ['created_at'],
            },
        ),
    ]
