# Generated by Django 4.0 on 2022-01-07 14:05

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='add_position_password',
            field=models.CharField(default='JYZUI', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='', regex=re.compile('^[0-9A-Z]+$'))], verbose_name='идентификатор'),
        ),
    ]
