# Generated by Django 4.0 on 2022-01-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='источник данных')),
                ('view_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='пароль для просмотра')),
                ('start_date', models.DateTimeField(verbose_name='дата начала')),
                ('end_date', models.DateTimeField(verbose_name='дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='устройство')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.customuser')),
            ],
            options={
                'verbose_name': 'трэк',
                'verbose_name_plural': 'трэки',
            },
        ),
        migrations.CreateModel(
            name='TrackPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='долгота (градусы)')),
                ('longitude_type', models.CharField(choices=[('E', 'Восточная'), ('W', 'Западная')], default='N', max_length=1, verbose_name='тип долготы')),
                ('latitude', models.FloatField(verbose_name='широта (градусы)')),
                ('latitude_type', models.CharField(choices=[('N', 'Северная'), ('S', 'Южная')], default='E', max_length=1, verbose_name='тип широты')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='расстояние (км)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='скорость (км/ч)')),
                ('acceleration', models.FloatField(blank=True, null=True, verbose_name='ускорение (м/с^2)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='время (с)')),
                ('is_broken', models.BooleanField(default=False, verbose_name='ложная точка')),
                ('parameters', models.TextField(blank=True, null=True, verbose_name='другие параметры')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='создан')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track', verbose_name='трек')),
            ],
            options={
                'verbose_name': 'точка трека',
                'verbose_name_plural': 'путевые точки треков',
                'ordering': ['created_at'],
            },
        ),
    ]
