# Generated by Django 4.0 on 2022-01-07 14:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.phonenumber


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='название правила')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email для извещений')),
                ('phone_number_sms', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^\\([0-9]{3}\\) [0-9]{3}-[0-9]{2}-[0-9]{2}$', message='(812) 123-45-67')], verbose_name='номер для СМС')),
                ('rule_type', models.PositiveIntegerField(choices=[(1, 'Гео-зона (выход)'), (2, 'Гео-зона (вход)'), (3, 'Начало движения'), (4, 'Максимальная скорость'), (5, 'Пропала связь'), (6, 'Связь установлена')], verbose_name='тип правила')),
                ('max_speed', models.FloatField(blank=True, null=True, verbose_name='порог скорости (км/ч)')),
                ('initial_longitude', models.FloatField(blank=True, null=True, verbose_name='долгота (градусы)')),
                ('initial_latitude', models.FloatField(blank=True, null=True, verbose_name='широта (градусы)')),
                ('distance_offset', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.025), django.core.validators.MaxValueValidator(25)], verbose_name='радиус зоны (км)')),
                ('auto_reactivate', models.BooleanField(default=False, help_text='После срабатывания активируется вновь', verbose_name='авто активация')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='дата активации')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='дата деактивации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='устройство')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.customuser')),
            ],
            options={
                'verbose_name': 'правило',
                'verbose_name_plural': 'правила',
            },
            bases=(models.Model, utils.phonenumber.PhoneNumber),
        ),
    ]
