# Generated by Django 4.0 on 2022-01-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('view_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='пароль для просмотра')),
                ('add_event_password', models.CharField(default='30BG21UWQSX5YJL3B20B', max_length=255, verbose_name='пароль для добавления событий')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('longitude', models.FloatField(blank=True, default=30.313497, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, default=59.938531, null=True, verbose_name='широта')),
                ('zoom', models.IntegerField(blank=True, default=11, null=True, verbose_name='масштаб')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('devices', models.ManyToManyField(blank=True, to='devices.Device', verbose_name='устройства на карте')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.customuser')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': 'карты',
            },
        ),
    ]
